name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: 📥 Checkout do repositório
        uses: actions/checkout@v3

      - name: 📦 Setup do Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: 📚 Instalar dependências
        run: npm ci

      - name: 🗃 Criar pasta do banco de dados (caso não exista)
        run: mkdir -p bd

      - name: 🧱 Criar banco de produção (esmforum.db)
        run: |
          if [ -f ./bd/esmforum.db ]; then
            echo "🧨 Arquivo esmforum.db já existe. Apagando..."
            rm ./bd/esmforum.db
          fi
          sqlite3 ./bd/esmforum.db < ./bd/schema.sql

      - name: 🧪 Criar banco de testes (esmforum-teste.db)
        run: |
          if [ -f ./bd/esmforum-teste.db ]; then
            echo "🧨 Arquivo esmforum-teste.db já existe. Apagando..."
            rm ./bd/esmforum-teste.db
          fi
          sqlite3 ./bd/esmforum-teste.db < ./bd/schema.sql

      - name: ✅ Rodar testes
        run: npm test
